---

- name: Fail if required Calibre-web settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - calibre-web_identifier
    - calibre-web_uid
    - calibre-web_gid
    - calibre-web_hostname
    - calibre-web_path_prefix
    - calibre-web_container_network

- when: calibre-web_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Calibre-web Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - calibre-web_container_labels_traefik_hostname
        - calibre-web_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `calibre-web_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if calibre-web_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          calibre-web_container_labels_traefik_path_prefix (`{{ calibre-web_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/calibre-web`).
      when: "calibre-web_container_labels_traefik_path_prefix != '/' and calibre-web_container_labels_traefik_path_prefix[-1] == '/'"
